steps:
# pull kubeconfig
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://cloud-lab/kubeconfig.yml', '.']
  waitFor: ['-']

# build wishlist
- name: 'gcr.io/cloud-builders/docker'
  id: image-build
  args: ['build', '--cache-from', 'gcr.io/$PROJECT_ID/wishlist', '-t', 'gcr.io/$PROJECT_ID/wishlist:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/wishlist', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: image-push
  waitFor: ['image-build']
  args: ['push', 'gcr.io/$PROJECT_ID/wishlist:$COMMIT_SHA']

# deploy wishlist
- name: 'gcr.io/trusted-builds/kubernetes-deploy'
  args: ['kubernetes-deploy', '${_NAMESPACE}', '${_CONTEXT}']
  waitFor: ['image-push']
  env:
  - 'KUBECONFIG=kubeconfig.yml'
  - 'ENVIRONMENT=production'
  - 'REVISION=$COMMIT_SHA'

substitutions:
  _CONTEXT: gke_kubesec_us-east4-b_lab
  _NAMESPACE: wishlist
images:
- gcr.io/$PROJECT_ID/wishlist
