name: wishlist

type: rails

up:
  - homebrew:
    - openssl
  - ruby: 2.6.4
  - bundler
  - railgun

server:
  port: 21120

commands:
  console: bin/rails console

open:
  "app": https://wishlist.myshopify.io
