name: wishlist

type: rails

up:
  - homebrew:
      - mysql-client@5.7:
          or: [mysql@5.7]
          conflicts: [mysql-connector-c, mysql, mysql-client]
    # - another_package
  - ruby: 2.7.2
  - node:
      version: v14.15.0
      yarn: 1.22.5
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: wishlist.railgun
      user: root
      password: ''
      database: wishlist_dev

server:
  port: 21120

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run: cd $USER_PWD && bin/rails test
  style:
    desc: 'Run rubocop lint checks'
    run: cd $USER_PWD && bundle exec rubocop
    subcommands:
      ruby:
        syntax:
          optional: --include-branch-commits --all-cops
        desc: 'Run Rubocop checks. Add --include-branch-commits to run on all files changed on the current branch. Add --all-cops to run all the cops.'
        run: cd $USER_PWD && bundle exec rubocop

open:
  "app": https://wishlist.myshopify.io
