# docker-compose file that runs postgres and pgadmin for my next applicationversion: '3.8'

services:
  postgres:
    image: postgres:17-alpine@sha256:c5da6bc9da9e3a3b6dc85585078c05c002c2d4deeaca00479f5571e2d00ca5d2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/wishlist"
      DIRECT_URL: "postgres://postgres:postgres@postgres:5432/wishlist"
      AUTH_TRUST_HOST: "true"
    ports:
      - 3000:3000

volumes:
  postgres-data:
