# docker-compose file that runs postgres and pgadmin for my next applicationversion: '3.8'

services:
  postgres:
    image: postgres:18-alpine@sha256:f898ac406e1a9e05115cc2efcb3c3abb3a92a4c0263f3b6f6aaae354cbb1953a
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/wishlist"
      DIRECT_URL: "postgres://postgres:postgres@postgres:5432/wishlist"
      AUTH_TRUST_HOST: "true"
    ports:
      - 3000:3000

volumes:
  postgres-data:
