# Run ./bootstrap.sh before running `docker-compose up`

version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wishlist"
      MYSQL_USER: "wishlist"
      MYSQL_PASSWORD: "wishlist"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u $$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      timeout: 20s
      retries: 10
  wishlist:
    build: .
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 6cdb3f1f380de54412912cdaaae2e30b
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_LOG_TO_STDOUT: 1
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: unless-stopped
