apiVersion: v1
kind: ServiceAccount
metadata:
  name: wishlist
  namespace: wishlist
  labels:
    app.kubernetes.io/name: wishlist
    app.kubernetes.io/part-of: wishlist
  annotations:
    iam.gke.io/gcp-service-account: wishlist@wishlist-4362e.iam.gserviceaccount.com
