apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wishlist
  namespace: wishlist
  labels:
    app.kubernetes.io/name: wishlist
    app.kubernetes.io/part-of: wishlist
spec:
  secretName: wishlist-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: wishin.app
  dnsNames:
  - wishin.app
  - www.wishin.app
