apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wishlist
  namespace: wishlist
  labels:
    app.kubernetes.io/name: wishlist
    app.kubernetes.io/part-of: wishlist
spec:
  secretName: wishlist-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: wishlist.srsly.ca
  dnsNames:
  - wishlist.srsly.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - wishlist.srsly.ca
    - http01:
        ingress: wishlist
      domains:
      - wishlist.srsly.ca
