/**
 * Static image imports (`import icon from '@/public/santaicon.png'`).
 *
 * Next declares these in `next-env.d.ts`, which is generated by `next dev` /
 * `next build` and gitignored — so a fresh checkout cannot typecheck until
 * someone has run a build. Referencing the same declarations from a committed
 * file makes `tsc --noEmit` work from a clean clone.
 */
/// <reference types="next/image-types/global" />
