# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: wishlist.railgun
  port: 3306
  read_timeout: 60
  write_timeout: 60

development:
  <<: *default
  database: wishlist_dev

test:
  <<: *default
  database: wishlist_test

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:database_url) %>
