#!/usr/bin/env bash
# Sourced by mise (mise.toml -> [env]._.source).
#
# Prisma publishes no schema engine for the linux-nixos target, so on NixOS
# `prisma db push` needs the nixpkgs build. This resolves it (and Postgres) out
# of the store once, caches the paths, and exports them — so `bunx --bun
# prisma`, `bun run build` and the db:* tasks work in a plain shell, with no
# `nix develop` wrapper around every command.
#
# Off NixOS (CI, Vercel, a container) there is no nix and nothing is exported;
# Prisma's own downloaded engine is correct there.

root="${MISE_PROJECT_ROOT:-$PWD}"
cache="$root/.mise/.cache/nix-paths.env"

# Rebuild the cache when it is missing, older than the flake, or pointing at a
# store path that has since been garbage collected.
_stale=0
if [ ! -f "$cache" ]; then
  _stale=1
elif [ "$root/flake.lock" -nt "$cache" ] || [ "$root/flake.nix" -nt "$cache" ]; then
  _stale=1
elif ! grep -q '^export PRISMA_SCHEMA_ENGINE_BINARY=' "$cache" 2>/dev/null; then
  _stale=1
else
  # Both paths, not just the engine: Postgres gets collected on its own and a
  # cache that survives the check still points PGBIN at nothing.
  for _var in PRISMA_SCHEMA_ENGINE_BINARY PGBIN; do
    _bin="$(sed -n "s/^export ${_var}=//p" "$cache")"
    [ -e "$_bin" ] || _stale=1
  done
fi

if [ "$_stale" = 1 ]; then
  if command -v nix >/dev/null 2>&1 && [ -f "$root/flake.nix" ]; then
    # postgresql is multi-output; ^out picks the one with the binaries.
    _engines="$(nix build --no-link --print-out-paths "$root#prisma-engines" 2>/dev/null | head -1)"
    _postgres="$(nix build --no-link --print-out-paths "$root#postgresql^out" 2>/dev/null | head -1)"
    if [ -n "$_engines" ] && [ -n "$_postgres" ]; then
      mkdir -p "$(dirname "$cache")"
      {
        echo "# Generated by .mise/nix-env.sh — do not edit, delete to refresh."
        echo "export PRISMA_SCHEMA_ENGINE_BINARY=$_engines/bin/schema-engine"
        echo "export PGBIN=$_postgres/bin"
      } >"$cache"
    fi
  fi
fi

# shellcheck disable=SC1090
[ -f "$cache" ] && . "$cache"

unset _stale _bin _engines _postgres root cache
