name: ci
on: [push]
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: Shopify/gh-action-hadolint@master
    - name: Build Dockerfile
      env:
        RAILS_ENV: production
      run: |
        docker build -t jonpulsifer/wishlist-rails:${{ github.sha }} .
    # This is producing false positives, disable for now
    # - name: Container security scan
    #   uses: Azure/container-scan@v0
    #   with:
    #     image-name: jonpulsifer/wishlist-rails:${{ github.sha }}
  ruby:
    name: Ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: install dependencies
        run: |
          gem install bundler --no-document
          bundle install
      - name: Lint (rubocop)
        run: bundle exec rubocop
      - name: Type Check (sorbet)
        run: bundle exec srb tc
