name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_ID }}
      NEXT_TELEMETRY_DISABLED: 1
      TURBO_TELEMETRY_DISABLED: 1
    services:
      postgres:
        image: postgres:18@sha256:073e7c8b84e2197f94c8083634640ab37105effe1bc853ca4d5fbece3219b0e8
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: pnpm
          node-version: 22

      - name: Prepare db & env files
        env:
          PGPASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_MULTIPLE_DATABASES: wishlist
        run: |
          ./.github/scripts/create-multiple-postgresql-databases.sh
          find . -type f -name '.env.example' -execdir cp -v {} .env \;

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm lint

      - name: Build
        run: pnpm build